/**
* 
* @author Miguel Maria Vazquez Martinez
* Sixth practice of module PMDM.
* 
*/

package View;

import Controller.AccessDB;
import Controller.QueryUserAccess;
import Errors.*;
import Model.Lawyer;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.UIManager;

public class FrameAccess extends javax.swing.JFrame {

    /**
     * Creates new form FrameAccess.
     */
    public FrameAccess() {
        try {
            AccessDB.closeConnection(conn);
            conn = AccessDB.getConnection();
            initComponents();
            
            /**
             * This try block check if the application is connected with the data base
             * and change de fram icon. The frame icon will be green if the application
             * is connected or red in other case.
             */
            if(conn != null && !conn.isClosed()){
                setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/greenDot.png")).getImage());
            } else {
                setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/redDot.png")).getImage());
                textFieldUser.setEnabled(false);
                textFieldPassword.setEnabled(false);
                buttonAcept.setEnabled(false);
            }
            charPassword = textFieldPassword.getEchoChar();
            pack();
        } catch (SQLException ex) {
            ErrorsSaveLogs.saveLogError(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelLogo = new javax.swing.JLabel();
        labelAccessMsg = new javax.swing.JLabel();
        labelHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textFieldPassword = new javax.swing.JPasswordField();
        textFieldUser = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        buttonAcept = new javax.swing.JButton();
        labelShowPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIAR SESIÓN");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/adaIcon.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelMain.setBackground(new java.awt.Color(255, 255, 255));

        panelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adaLogo.png"))); // NOI18N

        labelAccessMsg.setBackground(new java.awt.Color(255, 255, 255));
        labelAccessMsg.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelAccessMsg.setForeground(new java.awt.Color(255, 51, 51));
        labelAccessMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelHeader.setBackground(new java.awt.Color(255, 255, 255));
        labelHeader.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(0, 50, 71));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader.setText("INICIO DE SESIÓN");

        jSeparator1.setForeground(new java.awt.Color(0, 50, 71));

        textFieldPassword.setBackground(new java.awt.Color(204, 204, 204));
        textFieldPassword.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textFieldPassword.setForeground(new java.awt.Color(0, 50, 71));

        textFieldUser.setBackground(new java.awt.Color(204, 204, 204));
        textFieldUser.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textFieldUser.setForeground(new java.awt.Color(0, 50, 71));

        labelUser.setBackground(new java.awt.Color(255, 255, 255));
        labelUser.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelUser.setForeground(new java.awt.Color(0, 50, 71));
        labelUser.setText("USUARIO:");

        labelPassword.setBackground(new java.awt.Color(255, 255, 255));
        labelPassword.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(0, 50, 71));
        labelPassword.setText("CONTRASEÑA:");

        buttonAcept.setBackground(new java.awt.Color(0, 50, 71));
        buttonAcept.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        buttonAcept.setForeground(new java.awt.Color(255, 255, 255));
        buttonAcept.setText("Aceptar");
        buttonAcept.setBorder(null);
        buttonAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptActionPerformed(evt);
            }
        });
        buttonAcept.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonAceptKeyPressed(evt);
            }
        });

        labelShowPassword.setBackground(new java.awt.Color(255, 255, 255));
        labelShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eyeIconOFF.png"))); // NOI18N
        labelShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelShowPasswordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelShowPasswordMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMainLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(panelLogo))
                        .addGroup(panelMainLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(labelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelShowPassword)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(buttonAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelAccessMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(288, 288, 288)))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMainLayout.createSequentialGroup()
                    .addGap(244, 244, 244)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(labelAccessMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(84, 84, 84)
                    .addComponent(buttonAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptActionPerformed
        try {
            appAccess();
        } catch (ErrorsMsg ex) {
            ErrorsSaveLogs.saveLogError(ex.getMessage());
        }
    }//GEN-LAST:event_buttonAceptActionPerformed

    private void buttonAceptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonAceptKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                appAccess();
            } catch (ErrorsMsg ex) {
                ErrorsSaveLogs.saveLogError(ex.getMessage());
            }
        }
    }//GEN-LAST:event_buttonAceptKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            AccessDB.closeConnection(conn);
        } catch (SQLException ex) {
            ErrorsSaveLogs.saveLogError(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    private void labelShowPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelShowPasswordMousePressed

    }//GEN-LAST:event_labelShowPasswordMousePressed

    private void labelShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelShowPasswordMouseClicked
        /**
         * This method hide or show the password to assist the user.
         */
        if(showPassword){
            showPassword = false;
            labelShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eyeIconOFF.png")));
            textFieldPassword.setEchoChar(charPassword);
        } else {
            showPassword = true;
            labelShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eyeIconON.png")));
            textFieldPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_labelShowPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch (Exception E){}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAccess().setVisible(true);
            }
        });
    }    
    
    private void appAccess() throws ErrorsMsg{
        if("".equals(textFieldUser.getText()) || "".equals(String.valueOf(textFieldPassword.getPassword()))){
            labelAccessMsg.setText("Debe indicar Usuario y Contraseña.");
            textFieldPassword.setText("");
        } else if(QueryUserAccess.getAccess(conn, textFieldUser.getText(), String.valueOf(textFieldPassword.getPassword()))){
            this.user = QueryUserAccess.getUser();
            FrameApp app = new FrameApp();
            app.setVisible(true);
            this.setVisible(false);
        } else {
            labelAccessMsg.setText("Usuario o Contraseña incorrectos.");
            textFieldPassword.setText("");
        }
        
    }
    
    public void setFrameAccessVisible(boolean status){
        this.setVisible(status);
    }
    
    public static Lawyer getUser(){
        return user;
    }
    
    public static Connection getConnection(){
        return conn;
    }
    
    private static Connection conn;
    private static Lawyer user = new Lawyer();
    private static boolean showPassword = false;
    private static char charPassword;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcept;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAccessMsg;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelShowPassword;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel panelLogo;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPasswordField textFieldPassword;
    private javax.swing.JTextField textFieldUser;
    // End of variables declaration//GEN-END:variables
}
